# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run bash environment

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
      
jobs:
  run-shell:
    name: run shell script
    runs-on: self-hosted
    steps:
     - uses: actions/checkout@v2
     - name: run-script
       run: |
        my-shell Matias
