# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run bash environment

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
  
jobs:
  setup-wazuh-kibana-app:
    name: Run setup environment wazuh kibana app
    runs-on: self-hosted
    steps:
     - name: Setup environment variables
       run: |
        echo AQUI CONFIGURAMOS TODAS NUESTRAS VARIABLES
        
        echo head ref: ${{ github.head_ref }}
        echo base ref: ${{ github.base_ref }}
        
        echo "WAZUH_MANAGER_IMAGE=wazuh_manager_filebeat_sources_cmake" >> $GITHUB_ENV
        echo "WAZUH_AGENT_IMAGE=wazuh_agent_ubuntu_sources_cmake" >> $GITHUB_ENV
        echo "WAZUH_VERSION=v4.2.0-rc4" >> $GITHUB_ENV
        echo "ELASTIC_VERSION=7.10.2" >> $GITHUB_ENV

     - name: Muestro las variable step 1
       run: |
        echo Muestro las variable step 1: ${{ env.MIVARIABLE }} ${{ env.MIVARIABLE2 }} ${{ env.WAZUH_MANAGER_IMAGE }} ${{ env.ELASTIC_VERSION }}
     - name: Muestro las variable step 2
       run: |
        echo Muestro las variable step 2: ${{ env.MIVARIABLE }} ${{ env.MIVARIABLE2 }} ${{ env.WAZUH_MANAGER_IMAGE }} ${{ env.ELASTIC_VERSION }}
     - name: Download templates docker environment
       run: |
        echo Muestro las variable step 3: ${{ env.MIVARIABLE }} ${{ env.MIVARIABLE2 }} ${{ env.WAZUH_MANAGER_IMAGE }} ${{ env.ELASTIC_VERSION }}
        mkdir /home/matias/Documentos/github-actions-workflow/
        cd /home/matias/Documentos/github-actions-workflow/
        git clone https://${{ secrets.TOKEN }}@github.com/frankeros/wazuh-app-environments.git && cd wazuh-app-environments/
        mkdir packages
     - name: Starting containers
       run: |
        cd /home/matias/Documentos/github-actions-workflow/wazuh-app-environments/templates_elastic_prod/es_basic-wz_cluster-agent
        docker-compose up -d
     - name: Building package
       run: |
        cd /home/matias/Documentos/github-actions-workflow/
        git clone https://github.com/wazuh/wazuh-packages && cd wazuh-packages/wazuhapp
        git checkout 4.2
        ./generate_wazuh_app.sh -b v4.2.0-7.10.2 -s /home/matias/Documentos/github-actions-workflow/wazuh-app-environments/packages -r 1
     - name: Installing package
       run: |
        cd /home/matias/Documentos/github-actions-workflow/wazuh-app-environments/templates_elastic_prod/es_basic-wz_cluster-agent
        docker exec es_basic-wz_cluster-agent_kibana_1 bin/kibana-plugin install file:///packages/wazuh_kibana-4.2.0_7.10.2-1.zip
        docker-compose restart kibana
